### ISSUE TITLE
Uninstall icon when tap and hold on app

### ISSUE THREAD

**Issue by defrivm** [ohwgiles/focal#76] opened 2019-05-04 17:22 UTC
There is only app info and edit button when tap & hold on app. Need uninstall button also.

**Comment by ohwgiles** [comment] 2019-05-05 05:38
Normally the uninstall feature is provided by your distribution’s package manager (such as apt on Ubuntu). Focal is still in early development and as far as I’m aware isn’t packaged for any distributions. Perhaps if you could describe your environment in more detail (Distribution, GNOME/KDE/other) and ideally provide screenshots of current behaviour vs expected behaviour of another app then maybe I will understand exactly what is missing

**Comment by ohwgiles** [comment] 2019-07-25 17:14
Closing due to lack of information

**Closed as completed by ohwgiles** 2019-07-25 17:14 UTC
